module.exports = {
  crow: '德國能源署',
  earth: '國際再生能源署',
  kangaroo: '澳洲能源及環境政府部門',
  bear: '臺灣能源局',
  eagle: '美國能源資訊管理局',
  denmark: '丹麥風力發電案例',
  germany: '德國在地發電案例',
  netherland: '荷蘭生質能案例',
  drop: '臺灣雨水ph値觀測',
  cloud: '環保署空氣品質監測網',
  bolt: '國家能源消費統計',
  meter: '臺灣即時發電量資訊',
  money: '台電公開資訊',
  saving: '綠電合作社介紹',
  taiwan: '臺灣空氣品質地圖 PM2.5',
  potential: '臺灣再生能源潛力',
  network: '公民電廠陽光伏特家',
  factory: '臺灣發電現況',
  emission: '臺灣十大溫室氣體排放源',
};
